#---------------------------------------------------------------------------
# Copyright (c) 2022 TUM. All rights reserved.
#---------------------------------------------------------------------------
version: '2'

services:
  txbench-umbra:
    image: ghcr.io/umbra-db/colibri-vldb2024/umbra
    environment:
      - POSTGRES_PASSWORD=postgres
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
      - TRACE=${TRACE}
      - USEDIRECTIO=1
      - BUFFERSIZE=128G
    ports:
      - "25432:5432"
    privileged: true
    volumes:
      - ${WORKING_DIR}/txbench/db:/db
      - ${WORKING_DIR}/txbench/output:/output
      - ${WORKING_DIR}/txbench/data:/data
    networks:
      txbench:
        ipv4_address: 172.42.0.100
    cpuset: "0-63"
  txbench:
    image: ghcr.io/umbra-db/colibri-vldb2024/txbench
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
      - TRACE=${TRACE}
    privileged: true
    volumes:
      - ${WORKING_DIR}/txbench/scripts:/txbench/scripts
      - ${WORKING_DIR}/txbench/output:/txbench/output
      - ${WORKING_DIR}/txbench/config:/txbench/config
      - ${WORKING_DIR}/txbench/data:/data
    depends_on:
      - txbench-umbra
    networks:
      txbench:
        ipv4_address: 172.42.0.200
networks:
  txbench:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.0.0/16
          gateway: 172.42.0.1
